version: 2.1
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0

    working_directory: ~/repo

    environment:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1

    steps:
      - checkout

      - run: |
          mkdir /tmp/artifact &&
          dotnet publish app/app.csproj -c Debug -o /tmp/artifact --os win-x64

      - persist_to_workspace:
          root: /tmp/artifact
          paths:
            - '*'

      - store_artifacts:
          path: /tmp/artifact

  veracode-scan:
    docker:
      - image: veracode/api-wrapper-java:latest
    
    steps:
      - attach_workspace:
          at: /tmp/artifact

      - run: |
          zip -r /tmp/package.zip /tmp/artifact/* &&
          java -jar /opt/veracode/api-wrapper.jar \
            -vid ${VCUSER} \
            -vkey ${VCUSERKEY} \
            -action UploadAndScan \
            -createprofile true \
            -filepath /tmp/package.zip \
            -appname "${VCPREFIX}${CIRCLE_PROJECT_REPONAME}" \
            -version "${CIRCLE_SHA1}"
workflows:
  btd:
    jobs:
      - build
      - veracode-scan:
          requires:
            - build