version: 2.1
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0

    working_directory: ~/repo

    environment:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1

    steps:
      - checkout

      - run: |
          dotnet build app/app.csproj -c Release &&
          mkdir /tmp/artifact &&
          mv -f app/bin /tmp/artifact &&
          mv -f app/obj /tmp/artifact

      - persist_to_workspace:
          root: /tmp/artifact
          paths:
            - '*'

      - store_artifacts:
          path: /tmp/artifact